### ISSUE TITLE
workflow for milestone 3

### ISSUE THREAD

**Issue by heathervant** [UBC-MDS/Sustainability_Survey#29]
- [x] Find confounders with ANOVA- Heather

- [x] Write introduction of report- Marcelle

- [x] Ordinal analysis- Marcelle

- [x] ~Linear regression analysis- Kera~ (response variable is categorical - frequency of recycling)

- [x] Ordinal analysis with interaction- Kera

- [x] Refine EDA- Wilson

- [x] write question and methods of collection and analysis- Heather

- [x] Discuss results together and write discussion and conclusion. focus on conclusion and how study design influenced the conclusion. - everyone

- [x] What did we do well and how did that affect our conclusion. what would we do better? - everyone

notes- design of study helped and not using survey monkey 
-choice of scale from 1-10 and stratification for ordinal regression

**Comment by mchiriboga** [comment]
Items 2 and 3 addressed by https://github.com/UBC-MDS/Sustainability_Survey/pull/31 and https://github.com/UBC-MDS/Sustainability_Survey/pull/33 respectively
