### ISSUE TITLE
Milestone work flow

### ISSUE THREAD

**Issue by xiaoweideng** [UBC-MDS/Sustainability_Survey#6]
Hi team,

As we discussed before, I have changed our target question to "Does a person’s frequency of recycling influence her/his opinion and attitudes towards the importance of sustainability?"

Please read through my draft proposal and thumb up if you agree.

Here are some things you need to do:

- [x] Elaborate "Plan for analyzing the survey results" section and explain why we plan to include confounding variables. @K3ra-y 

- [x] Write an introduction paragraph about why we choose the topic. @heathervant 

- [x] Write "Aspects of the UBC Office of Research Ethics document on Using Online Surveys that are relevant to our survey" section. @mchiriboga 

Also, please proofread the draft. Thank you for your support.

**Comment by mchiriboga** [comment]
Items addressed on [Milestone 1 release](https://github.com/UBC-MDS/Sustainability_Survey/releases/tag/v1.0)
